;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Child 1",NewTagName="Small Child 1")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Medium Child 1",DevComment="")
+GameplayTagList=(Tag="Medium Child 2",DevComment="")
+GameplayTagList=(Tag="Small Child 1",DevComment="")
+GameplayTagList=(Tag="Small Child 2",DevComment="")

